name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
        

    - name: Linting 
      run: |
        flake8 . --max-line-length=139 --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Unit testing
      run: python3 -m pytest tests
