name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: DVC setup
      uses: iterative/setup-dvc@v1

    - name: Install dependencies
      run: |
        python -m pip install -U setuptools pip
        pip install flake8
        pip install -r requirements.txt
        pip install dvc[s3]
 
    - name: Pull DVC
      run: dvc pull

    - name: Linting 
      run: flake8 . --max-line-length=139 --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Unit testing
      run: python3 -m pytest tests
